{
  parserClass="com.github.zhongkunming.sql.DamengSQLParser"
  parserUtilClass="com.intellij.lang.parser.GeneratedParserUtilBase"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
  psiClassPrefix="Dameng"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.zhongkunming.sql.psi"
  psiImplPackage="com.github.zhongkunming.sql.psi.impl"
  elementTypeHolderClass="com.github.zhongkunming.sql.psi.DamengSQLTypes"
  elementTypeClass="com.github.zhongkunming.sql.psi.DamengSQLElementType"
  tokenTypeClass="com.github.zhongkunming.sql.psi.DamengSQLTokenType"
  mixin(".*Statement")="com.github.zhongkunming.sql.psi.DamengSQLStatementMixin"
  tokens = [
    SELECT='SELECT'
  ]
}

dualStatement ::= DUAL
