{
  parserClass="com.github.zhongkunming.dameng.DmParser"
  parserUtilClass="com.intellij.lang.parser.GeneratedParserUtilBase"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
  psiClassPrefix="Dm"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.zhongkunming.dameng.psi"
  psiImplPackage="com.github.zhongkunming.dameng.psi.impl"
  elementTypeHolderClass="com.github.zhongkunming.dameng.DmTypes"
  elementTypeClass="com.github.zhongkunming.dameng.DmElementTypes"
  tokenTypeClass="com.github.zhongkunming.dameng.DmTokenType"
  tokens = [
    SELECT='SELECT'
  ]
}

dualStatement ::= DUAL
